name: Laravel CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: laravel_todo_list_test
          POSTGRES_USER: luongcongduy
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Laravel project
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, intl, bcmath, pdo_pgsql
          init-values: post_max_size=256M, max_execution_time=300
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Create .env.testing
        run: |
          cp .env.example .env.testing
          echo "DB_CONNECTION=pgsql" >> .env.testing
          echo "DB_HOST=127.0.0.1" >> .env.testing
          echo "DB_PORT=5432" >> .env.testing
          echo "DB_DATABASE=laravel_todo_list_test" >> .env.testing
          echo "DB_USERNAME=luongcongduy" >> .env.testing
          echo "DB_PASSWORD=password" >> .env.testing

      - name: Generate application key
        run: php artisan key:generate --env=testing

      - name: Run database migrations
        run: php artisan migrate --env=testing

      - name: Run tests
        run: php artisan test
